###### Настройки терминала ######

# Название терминала
#TERMINAL_NAME: [PAM]-{HOSTNAME}

# Описание терминала
#TERMINAL_COMMENT: Pam terminal

# Адрес основного сервера (api)
#CORE_HOST: http://localhost:8080

# Токен подключения терминала к основному серверу
#BOOTSTRAP_TOKEN:

# Уровень логов [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
#LOG_LEVEL: INFO